/**
 * Chrono-Express Levels & Missions Data
 * 12 Missions aligned with IPST / สสวท. Grade 4 Time Curriculum
 * Features clean station names, departure/arrival times, and concise story briefs.
 */

window.CHRONO_LEVELS = [
  // ==========================================
  // ชุมทางที่ 1: ชานชาลาแสงแรก (Dawn Junction)
  // ==========================================
  {
    id: 1,
    junction: 1,
    junctionName: 'ชุมทางแสงแรก',
    title: 'ขบวนด่วนสายอรุณรุ่ง',
    badge: '🌅 ตราดวงตะวันแรก',
    story: 'ปล่อยยานส่งจดหมายดวงดาวรอบเช้าตรู่ในระบบ 24 ชั่วโมง',
    type: 'set_time',
    departureStation: 'ท่าอวกาศอรุณรุ่ง',
    arrivalStation: 'ชุมทางดาวพุธ',
    departureTimeText: '07:15 น.',
    arrivalTimeText: '08:30 น.',
    durationText: '1 ชม. 15 นาที',
    initialTime: { hours: 6, minutes: 0 },
    targetTime: { hours: 7, minutes: 15 },
    targetDisplay: '07:15 น.',
    targetSubText: 'เจ็ดโมงเช้าสิบห้านาที (กลางวัน)',
    hint: 'กลางวัน 7 โมงเช้า = 07:00 น. หมุนเข็มยาวไปเลข 3 นะ!',
    concept: 'เวลากลางวันเริ่ม 06:00 น. ถึง 18:00 น. 7 โมงเช้า 15 นาที เขียนเป็น 07:15 น.'
  },
  {
    id: 2,
    junction: 1,
    junctionName: 'ชุมทางแสงแรก',
    title: 'ขบวนเสบียงบ่ายสาม',
    badge: '🍎 ตราผลไม้ทองคำ',
    story: 'เตรียมรับยานขนส่งเสบียงเวลาบ่าย 3 โมง 40 นาที',
    type: 'set_time',
    departureStation: 'สถานีสวนสวรรค์',
    arrivalStation: 'ท่าอวกาศกลาง',
    departureTimeText: '14:00 น.',
    arrivalTimeText: '15:40 น.',
    durationText: '1 ชม. 40 นาที',
    initialTime: { hours: 12, minutes: 0 },
    targetTime: { hours: 15, minutes: 40 },
    targetDisplay: '15:40 น.',
    targetSubText: 'บ่ายสามโมงสี่สิบนาที (กลางวัน)',
    hint: 'บ่าย 3 โมง ให้นำ 12 + 3 = 15:00 น. เข็มยาวชี้เลข 8!',
    concept: 'หลังเที่ยงวัน (12:00) ให้นับต่อ: บ่าย 1 = 13:00, บ่าย 2 = 14:00, บ่าย 3 = 15:00 น.'
  },
  {
    id: 3,
    junction: 1,
    junctionName: 'ชุมทางแสงแรก',
    title: 'ขบวนแสงจันทร์สองทุ่ม',
    badge: '🌙 ตราแสงจันทร์นวล',
    story: 'เปิดสัญญาณไฟให้ขบวนแสงจันทร์เวลากลางคืน 2 ทุ่ม 25 นาที',
    type: 'set_time',
    departureStation: 'ท่าอวกาศจันทรา',
    arrivalStation: 'ชุมทางดาวพฤหัส',
    departureTimeText: '20:25 น.',
    arrivalTimeText: '22:10 น.',
    durationText: '1 ชม. 45 นาที',
    initialTime: { hours: 18, minutes: 0 },
    targetTime: { hours: 20, minutes: 25 },
    targetDisplay: '20:25 น.',
    targetSubText: 'สองทุ่มยี่สิบห้านาที (กลางคืน)',
    hint: 'กลางคืน 2 ทุ่ม = 18 + 2 = 20:00 น. หมุนเข็มยาวไปเลข 5!',
    concept: 'เวลากลางคืนเริ่ม 18:00 น. ถึง 06:00 น. สังเกตว่า 2 ทุ่ม = 20:00 น.'
  },

  // ==========================================
  // ชุมทางที่ 2: หุบเขาฟันเฟือง 60 (Gear Valley)
  // ==========================================
  {
    id: 4,
    junction: 2,
    junctionName: 'หุบเขาฟันเฟือง 60',
    title: 'ฟันเฟือง 95 นาที',
    badge: '⚙️ ตราฟันเฟืองทองเหลือง',
    story: 'ยานวิ่งสะสมเวลาได้ 95 นาที จงแปลงเป็นชั่วโมงและนาที',
    type: 'convert_units',
    departureStation: 'โรงช่างกลฟันเฟือง',
    arrivalStation: 'ท่าอวกาศทดลอง',
    departureTimeText: '09:00 น.',
    arrivalTimeText: '10:35 น.',
    durationText: '95 นาที',
    inputMinutes: 95,
    expectedHours: 1,
    expectedMinutes: 35,
    targetDisplay: '1 ชม. 35 นาที',
    targetSubText: 'ใส่ตัวเลข 1 ชั่วโมง กับ 35 นาที',
    hint: '1 ชั่วโมง = 60 นาที หัก 95 - 60 = เหลือ 35 นาที!',
    concept: '95 นาที = 60 นาที + 35 นาที = 1 ชั่วโมง 35 นาที'
  },
  {
    id: 5,
    junction: 2,
    junctionName: 'หุบเขาฟันเฟือง 60',
    title: 'ขบวนด่วนข้ามขุนเขา',
    badge: '🏔️ ตรายอดเขาสูง',
    story: 'ออก 09:30 น. ใช้เวลา 1 ชม. 45 นาที คำนวณเวลาถึงปลายทาง',
    type: 'calculate_arrival',
    departureStation: 'สถานีเชิงผา',
    arrivalStation: 'ยอดเขาดวงดาว',
    departureTimeText: '09:30 น.',
    arrivalTimeText: '11:15 น.',
    durationText: '1 ชม. 45 นาที',
    departure: { hours: 9, minutes: 30 },
    durationMin: 105,
    targetTime: { hours: 11, minutes: 15 },
    targetDisplay: '11:15 น.',
    targetSubText: 'สิบเอ็ดนาฬิกาสิบห้านาที',
    hint: '09:30 + 1 ชม. = 10:30 น. บวกอีก 45 นาที = 11:15 น.!',
    concept: '30 นาที + 45 นาที = 75 นาที ทด 60 นาทีเป็น 1 ชั่วโมง เหลือเศษ 15 นาที'
  },
  {
    id: 6,
    junction: 2,
    junctionName: 'หุบเขาฟันเฟือง 60',
    title: 'ขบวนผลึกคริสตัล',
    badge: '💎 ตราผลึกคริสตัล',
    story: 'ออก 13:40 น. ใช้เวลา 2 ชม. 30 นาที คำนวณเวลาถึงปลายทาง',
    type: 'calculate_arrival',
    departureStation: 'เหมืองคริสตัล',
    arrivalStation: 'สถานีวิจัยกลาง',
    departureTimeText: '13:40 น.',
    arrivalTimeText: '16:10 น.',
    durationText: '2 ชม. 30 นาที',
    departure: { hours: 13, minutes: 40 },
    durationMin: 150,
    targetTime: { hours: 16, minutes: 10 },
    targetDisplay: '16:10 น.',
    targetSubText: 'สิบหกนาฬิกาสิบนาที',
    hint: '13:40 + 2 ชม. = 15:40 น. บวกอีก 30 นาที ได้ 16:10 น.',
    concept: '40 นาที + 30 นาที = 70 นาที ทด 60 นาทีไปเป็น 1 ชั่วโมง เหลือ 10 นาที'
  },

  // ==========================================
  // ชุมทางที่ 3: อุโมงค์ข้ามกาลเวลา (Time Warp Tunnel)
  // ==========================================
  {
    id: 7,
    junction: 3,
    junctionName: 'อุโมงค์กาลเวลา',
    title: 'วัดระยะเวลาในอุโมงค์',
    badge: '🌀 ตราเกลียวกาลเวลา',
    story: 'เข้าอุโมงค์ 08:15 น. ถึง 11:45 น. คำนวณระยะเวลาที่ใช้',
    type: 'calculate_duration',
    departureStation: 'ปากอุโมงค์กาลเวลา',
    arrivalStation: 'ปลายทางมิติใหม่',
    departureTimeText: '08:15 น.',
    arrivalTimeText: '11:45 น.',
    durationText: 'คำนวณระยะเวลา',
    departure: { hours: 8, minutes: 15 },
    arrival: { hours: 11, minutes: 45 },
    expectedHours: 3,
    expectedMinutes: 30,
    targetDisplay: '3 ชม. 30 นาที',
    targetSubText: 'ใส่ตัวเลข 3 ชั่วโมง กับ 30 นาที',
    hint: 'นำเวลาถึง ลบ เวลาออก: 11:45 - 08:15 = 3 ชม. 30 นาที!',
    concept: 'ระยะเวลา = เวลาสิ้นสุด - เวลาเริ่มต้น'
  },
  {
    id: 8,
    junction: 3,
    junctionName: 'อุโมงค์กาลเวลา',
    title: 'ย้อนเวลาขบวนส่งด่วน',
    badge: '⏳ ตรานาฬิกาทรายย้อนกลับ',
    story: 'ต้องถึงปลายทาง 14:10 น. วิ่ง 1 ชม. 35 นาที ต้องออกกี่โมง?',
    type: 'calculate_departure',
    departureStation: 'ท่าส่งด่วนลับ',
    arrivalStation: 'พระราชวังดวงดาว',
    departureTimeText: '12:35 น.',
    arrivalTimeText: '14:10 น.',
    durationText: '1 ชม. 35 นาที',
    arrival: { hours: 14, minutes: 10 },
    durationMin: 95,
    targetTime: { hours: 12, minutes: 35 },
    targetDisplay: '12:35 น.',
    targetSubText: 'สิบสองนาฬิกาสามสิบห้านาที',
    hint: '14:10 ถอยหลัง 1 ชม. = 13:10 น. ถอยอีก 35 นาที = 12:35 น.!',
    concept: 'การลบเวลายืมฐาน 60: 14 ชม. 10 นาที ยืม 1 ชม. เป็น 13 ชม. 70 นาที แล้วลบ 1 ชม. 35 นาที'
  },
  {
    id: 9,
    junction: 3,
    junctionName: 'อุโมงค์กาลเวลา',
    title: 'ขบวนเสบียงอัสดง',
    badge: '🌄 ตราขอบฟ้าอัสดง',
    story: 'ถึง 17:05 น. วิ่ง 2 ชม. 50 นาที คำนวณเวลาที่ต้องออกเดินทาง',
    type: 'calculate_departure',
    departureStation: 'โอเอซิสดวงดาว',
    arrivalStation: 'ชุมทางตะวันตก',
    departureTimeText: '14:15 น.',
    arrivalTimeText: '17:05 น.',
    durationText: '2 ชม. 50 นาที',
    arrival: { hours: 17, minutes: 5 },
    durationMin: 170,
    targetTime: { hours: 14, minutes: 15 },
    targetDisplay: '14:15 น.',
    targetSubText: 'สิบสี่นาฬิกาสิบห้านาที',
    hint: 'ยืมเวลา: 17 ชม. 5 นาที = 16 ชม. 65 นาที ลบออก 2 ชม. 50 นาที = 14:15 น.!',
    concept: 'เมื่อนาทีตัวตั้งน้อยกว่า ให้กระจายชั่วโมงมา 1 ชม. ซึ่งเท่ากับ 60 นาทีเสมอ'
  },

  // ==========================================
  // ชุมทางที่ 4: ชุมทางดวงดาวเที่ยงคืน (Midnight Star Crossing)
  // ==========================================
  {
    id: 10,
    junction: 4,
    junctionName: 'ดวงดาวเที่ยงคืน',
    title: 'ขบวนดาวตกข้ามเที่ยงคืน',
    badge: '🌠 ตราดาวตกมหัศจรรย์',
    story: 'ออก 23:20 น. วิ่ง 1 ชม. 25 นาที จะถึงกี่โมงในวันใหม่?',
    type: 'calculate_arrival',
    departureStation: 'หอคอยราตรี',
    arrivalStation: 'รุ่งอรุณวันใหม่',
    departureTimeText: '23:20 น.',
    arrivalTimeText: '00:45 น. (วันใหม่)',
    durationText: '1 ชม. 25 นาที',
    departure: { hours: 23, minutes: 20 },
    durationMin: 85,
    targetTime: { hours: 0, minutes: 45 },
    targetDisplay: '00:45 น.',
    targetSubText: 'ศูนย์นาฬิกาสี่สิบห้านาที (วันใหม่)',
    hint: '23:20 วิ่งไป 40 นาที จะถึงเที่ยงคืน (00:00 น.) เหลืออีก 45 นาที ได้ 00:45 น.!',
    concept: 'เมื่อผ่าน 24:00 น. จะเริ่มนับวันใหม่ที่ 00:00 น.'
  },
  {
    id: 11,
    junction: 4,
    junctionName: 'ดวงดาวเที่ยงคืน',
    title: 'ปริศนารถไฟดึกสงัด',
    badge: '🦉 ตรานกฮูกราตรี',
    story: 'ถึง 01:15 น. วิ่ง 2 ชม. 15 นาที หาเวลาออกเดินทางของเมื่อคืน',
    type: 'calculate_departure',
    departureStation: 'มิติรัตติกาล',
    arrivalStation: 'ชุมทางรุ่งสาง',
    departureTimeText: '23:00 น. (เมื่อคืน)',
    arrivalTimeText: '01:15 น.',
    durationText: '2 ชม. 15 นาที',
    arrival: { hours: 1, minutes: 15 },
    durationMin: 135,
    targetTime: { hours: 23, minutes: 0 },
    targetDisplay: '23:00 น.',
    targetSubText: 'ยี่สิบสามนาฬิกาตรง (ห้าทุ่ม)',
    hint: '01:15 ถอย 1 ชม. 15 นาที จะถึง 00:00 น. ถอยต่ออีก 1 ชม. = 23:00 น.!',
    concept: 'การถอยเวลาย้อนข้ามเที่ยงคืน กลับสู่ 23:00 น. ของวันก่อนหน้า'
  },
  {
    id: 12,
    junction: 4,
    junctionName: 'ดวงดาวเที่ยงคืน',
    title: 'สุดยอดนายสถานีอวกาศ',
    badge: '👑 มงกุฎปรมาจารย์กาลเวลา',
    story: 'ยาน A ถึง 18:20 น. พัก 35 นาที ยาน B จึงออกได้ หาเวลาออกของยาน B',
    type: 'calculate_arrival',
    departureStation: 'สถานีกลางจักรวาล',
    arrivalStation: 'สุดขอบกาแล็กซี',
    departureTimeText: '18:55 น.',
    arrivalTimeText: '20:30 น.',
    durationText: 'พัก 35 นาที',
    departure: { hours: 18, minutes: 20 },
    durationMin: 35,
    targetTime: { hours: 18, minutes: 55 },
    targetDisplay: '18:55 น.',
    targetSubText: 'สิบแปดนาฬิกาห้าสิบห้านาที',
    hint: '18:20 + 35 นาที = 20 + 35 = 55 นาที ได้ 18:55 น.!',
    concept: 'การคำนวณตารางเวลาเดินรถไฟอวกาศ (Timetable Management) อย่างแม่นยำ'
  }
];
